version:  '3.1'

services: 
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    environment:  
      MYSQL_DATABASE: bookVaultDB
      MYSQL_USER: giuseppe
      MYSQL_PASSWORD: psw
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"

  php:
    build:
      context:  .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql